Homework8
MakAn7/Notes pull request #8
Opened 2022-06-06 15:22 UTC by MakAn7

2022-06-10 13:14 UTC, bsciosedu requested changes

2022-06-10 13:14 UTC, bsciosedu commented on Notes/DetailsToDo/DetailsToDoViewController.swift
> +    enum State {
Это надо вынести в presenter.

2022-06-10 13:14 UTC, bsciosedu commented on Notes/ListToDo/ListAssembly.swift
> +import Foundation
UIKit уже содержит в себе Foundation. 
Foundation можно удалить.

2022-06-10 13:14 UTC, bsciosedu commented on Notes/ListToDo/ListPresenter.swift
> +  weak var viewController: ListDisplayLogic?
Отступ 4 пробела

2022-06-10 13:14 UTC, bsciosedu commented on Notes/ListToDo/ListPresenter.swift
> +    func didpresentModelsFromDataBase(models: [ListCellViewModel]) {
Present должно быть с большой буквы.

2022-06-10 13:14 UTC, bsciosedu commented on Notes/ListToDo/ListRouter.swift
> +  weak var viewController: ListViewController?
Отступ должен быть 4

2022-06-13 09:25 UTC, MakAn7 commented on Notes/DetailsToDo/DetailsToDoAssembly.swift
> +        cell: ListCellViewModel,
Исправил .

2022-06-13 09:25 UTC, MakAn7 commented on Notes/DetailsToDo/DetailsToDoInteractor.swift
> +import UIKit
Убрал .

2022-06-13 09:25 UTC, MakAn7 commented on Notes/DetailsToDo/DetailsToDoPresenter.swift
> +import UIKit
Убрал .

2022-06-13 09:26 UTC, MakAn7 commented on Notes/DetailsToDo/DetailsToDoAssembly.swift
> +        let controller = DetailsToDoViewController(state: .edit(model: cell, indexRow: index), delegate: delegate)
Реализовал .

2022-06-13 09:33 UTC, MakAn7 commented on Notes/ListToDo/ListAssembly.swift
> +import Foundation
Готово .

2022-06-13 09:33 UTC, MakAn7 commented on Notes/ListToDo/ListPresenter.swift
> +  weak var viewController: ListDisplayLogic?
Исправил .

2022-06-13 09:33 UTC, MakAn7 commented on Notes/ListToDo/ListPresenter.swift
> +    func didpresentModelsFromDataBase(models: [ListCellViewModel]) {
Исправил .

2022-06-13 23:33 UTC, MakAn7 commented on Notes/DetailsToDo/DetailsToDoViewController.swift
> +    enum State {
Готово .

2022-06-15 15:25 UTC, merged